export const popularProducts = [
  {
    id: 1,
    name: "Premium Red Apple",
    image: "/popular-products/red-apple.webp",
    price: 14.99,
    oldPrice: 20.99,
    sale: 50,
    rating: 4.82,
    reviewCount: 347,
  },
  {
    id: 2,
    name: "Fresh Red Bell Pepper",
    image: "/popular-products/red-pepper.webp",
    price: 12.0,
    rating: 4.27,
    reviewCount: 238,
  },
  {
    id: 3,
    name: "Fresh Granny Smith Apple",
    image: "/popular-products/green-apple.webp",
    price: 15.0,
    rating: 4.17,
    reviewCount: 158,
    oldPrice: 30.99,
    sale: 50,
    badge: "Best Sale",
  },
  {
    id: 4,
    name: "Premium Indian Orange",
    image: "/popular-products/orange.webp",
    price: 20.0,
    rating: 3.67,
    reviewCount: 128,
  },
  {
    id: 5,
    name: "Organic Chinese Cabbage",
    image: "/popular-products/cabbage.webp",
    price: 12.5,
    rating: 4.24,
    reviewCount: 216,
  },
  {
    id: 6,
    name: "Fresh Green Leaf Lettuce",
    image: "/popular-products/lettuce.webp",
    price: 9.7,
    rating: 2.86,
    reviewCount: 43,
  },
  {
    id: 7,
    name: "Farm Fresh Eggplant",
    image: "/popular-products/eggplant.webp",
    price: 34.6,
    rating: 4.51,
    reviewCount: 291,
  },
  {
    id: 8,
    name: "Golden Fresh Potato",
    image: "/popular-products/potato.webp",
    price: 20.0,
    rating: 3.92,
    reviewCount: 184,
  },
  {
    id: 9,
    name: "Sweet Yellow Corn",
    image: "/popular-products/corn.webp",
    price: 20.2,
    rating: 4.73,
    reviewCount: 402,
  },
  {
    id: 10,
    name: "Fresh White Cauliflower",
    image: "/popular-products/cauliflower.webp",
    price: 12.9,
    rating: 3.41,
    reviewCount: 97,
  },
  {
    id: 11,
    name: "Green Bell Pepper",
    image: "/popular-products/capsicum.webp",
    price: 9,
    oldPrice: 20.99,
    sale: 50,
    rating: 4.17,
    reviewCount: 253,
  },
  {
    id: 12,
    name: "Fresh Green Chili",
    image: "/popular-products/chili.webp",
    price: 34.0,
    rating: 2.95,
    reviewCount: 58,
  },
  {
    id: 13,
    name: "Garden Fresh Cucumber",
    image: "/popular-products/cucumber.webp",
    price: 15.0,
    rating: 4.05,
    reviewCount: 163,
  },
  {
    id: 14,
    name: "Vine Ripe Tomato",
    image: "/popular-products/tomato.webp",
    price: 18.0,
    rating: 4.36,
    reviewCount: 274,
  },
  {
    id: 15,
    name: "Organic Orange Carrot",
    image: "/popular-products/carrot.webp",
    price: 16.0,
    rating: 3.82,
    reviewCount: 112,
  },
  {
    id: 16,
    name: "Fresh Red Onion",
    image: "/popular-products/onion.webp",
    price: 22.0,
    rating: 4.18,
    reviewCount: 209,
  },
  {
    id: 17,
    name: "Organic Ginger Root",
    image: "/popular-products/ginger.webp",
    price: 14.0,
    rating: 4.61,
    reviewCount: 332,
  },
];

export const latestNews = [
  {
    id: 1,
    title: "7 Benefits of Adding Fresh Citrus Fruits to Your Daily Diet",
    image: "/latest-news/orange.webp",
   tags : [
    {
       category: "Healthy Tips",
    author: "Admin",
    comments: 18,
    }
   ],
    day: 18,
    month: "NOV",
    slug: "benefits-of-fresh-citrus-fruits",
  },
  {
    id: 2,
    title: "5 Easy High-Protein Breakfast Ideas to Start Your Day",
    image: "/latest-news/egg-toast.webp",
    tags: [
      {
        category: "Recipes",
        author: "Admin",
        comments: 29,
      },
    ],
    day: 29,
    month: "JAN",
    slug: "high-protein-breakfast-ideas",
  },
  {
    id: 3,
    title: "How to Build a Balanced and Colorful Healthy Plate",
    image: "/latest-news/healthy-salad.webp",
    tags: [
      {
        category: "Nutrition",
    author: "Admin",
    comments: 21,
      }
    ],
    day: 21,
    month: "FEB",
    slug: "build-a-balanced-healthy-plate",
  },
];
